apiVersion: apps/v1
kind: Deployment
metadata:
 name: python-app
 labels:
   app: python-app
spec:
 replicas: 1  # You can adjust the number of replicas as needed
 selector:
   matchLabels:
     app: python-app
 template:
   metadata:
     labels:
       app: python-app
   spec:
     containers:
       - name: python-app-hello-world
         image: asia-south1-docker.pkg.dev/river-blade-408018/linu-artifact-repo/python-app:${{ needs.build.outputs.latest_tag }}
         imagePullPolicy: Always
         ports:
           - containerPort: 80
         readinessProbe:
           httpGet:
             path: /
             port: 8080   #app port
           initialDelaySeconds: 5
           timeoutSeconds: 5
           periodSeconds: 5
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  labels:
    app: python-app
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: python-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: session-static-ip
spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-app-service
                port:
                  number: 80
